version: '3'
services:
  nodejs:
    image: stdmnstar/nodejs
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres    
    environment:
      - PORT=${PORT} 
      - TZ=${TIME_ZONE}
    restart: always
    networks:
      - app-network  
    volumes:
      - ./logs:/user/app/logs
      - ./src:/user/app/src  

  postgres:
    image: stdmnstar/postgres
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}    
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}           
      - TZ=${TIME_ZONE}
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - app-network
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

networks:
  app-network:
    driver: bridge    
