version: '3'
services:
  nodejs:
    image: stdmnstar/nodejs
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    env_file: .env
    environment:
      - PORT=${PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}    
  postgres:
    image: stdmnstar/postgres
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: .env
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA="/var/lib/postgresql/data"
